# Set the port number for the application to 8080
server.port=8080
#
spring.profiles.active=default
# log
#logging:
#    level:
#        com.example.logbackdemo: debug # ???????debug????
##root: warn # root???warn????????debug????---????
#    file: logback-demo.log

logging.config=classpath:log4j2-spring.xml
logging.level.root=INFO
logging.level.com.example=DEBUG

spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=github_repos

spring.github.token=${GITHUB_TOKEN}
spring.github.user=${GITHUB_USER}

# additional application.properties
spring.config.additional-location=classpath:file-paths.properties

# repo path
project.config.dataset.path=/please config your dataset path in resources/application.properties/
project.config.output.path = /please config your output path in resources/application.properties/